//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassadFood.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HassadFood.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accomodation: *.
        /// </summary>
        internal static string Accomodation {
            get {
                return ResourceManager.GetString("Accomodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Comments:.
        /// </summary>
        internal static string AdditionalComments {
            get {
                return ResourceManager.GetString("AdditionalComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline Flight Number:.
        /// </summary>
        internal static string AirlineFlightNumber {
            get {
                return ResourceManager.GetString("AirlineFlightNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Ticket:.
        /// </summary>
        internal static string AirTicket {
            get {
                return ResourceManager.GetString("AirTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string AlertText {
            get {
                return ResourceManager.GetString("AlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amendment Request.
        /// </summary>
        internal static string AmendmentRequest {
            get {
                return ResourceManager.GetString("AmendmentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied Leave Dates: *.
        /// </summary>
        internal static string AppliedLeaveDates {
            get {
                return ResourceManager.GetString("AppliedLeaveDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Leave Dates: *.
        /// </summary>
        internal static string ApprovedLeaveDatesRq {
            get {
                return ResourceManager.GetString("ApprovedLeaveDatesRq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Date: *.
        /// </summary>
        internal static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget: *.
        /// </summary>
        internal static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Duration.
        /// </summary>
        internal static string CalculateDuration {
            get {
                return ResourceManager.GetString("CalculateDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Request.
        /// </summary>
        internal static string CancellationRequest {
            get {
                return ResourceManager.GetString("CancellationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class of Travel:.
        /// </summary>
        internal static string ClassofTravel {
            get {
                return ResourceManager.GetString("ClassofTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Travel: *.
        /// </summary>
        internal static string DateofTravel {
            get {
                return ResourceManager.GetString("DateofTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination / Route: *.
        /// </summary>
        internal static string DestinationRoute {
            get {
                return ResourceManager.GetString("DestinationRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Visit.
        /// </summary>
        internal static string DutyVisit {
            get {
                return ResourceManager.GetString("DutyVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Visit.
        /// </summary>
        internal static string EmployeeRequest {
            get {
                return ResourceManager.GetString("EmployeeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Upon completion of Duty Visit kindly handover the original Boarding Pass or Passport Stamp copy to HR for processing. This step is prerequisite for processing payment..
        /// </summary>
        internal static string EmployeeRequestNote {
            get {
                return ResourceManager.GetString("EmployeeRequestNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time:.
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Permit.
        /// </summary>
        internal static string ExitPermit {
            get {
                return ResourceManager.GetString("ExitPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Permit: *.
        /// </summary>
        internal static string ExitPermitLbl {
            get {
                return ResourceManager.GetString("ExitPermitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Day: *.
        /// </summary>
        internal static string FirstDayoftheDutyVisit {
            get {
                return ResourceManager.GetString("FirstDayoftheDutyVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Date:.
        /// </summary>
        internal static string FlightDate {
            get {
                return ResourceManager.GetString("FlightDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Date: *.
        /// </summary>
        internal static string FlightDateRq {
            get {
                return ResourceManager.GetString("FlightDateRq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Travel Time:.
        /// </summary>
        internal static string FlightTravelTime {
            get {
                return ResourceManager.GetString("FlightTravelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0C335A.
        /// </summary>
        internal static string HeaderButtonColor {
            get {
                return ResourceManager.GetString("HeaderButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justification:.
        /// </summary>
        internal static string Justification {
            get {
                return ResourceManager.GetString("Justification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justification: *.
        /// </summary>
        internal static string JustificationRq {
            get {
                return ResourceManager.GetString("JustificationRq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Of Letter *.
        /// </summary>
        internal static string LanguageOfLetter {
            get {
                return ResourceManager.GetString("LanguageOfLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Day: *.
        /// </summary>
        internal static string LastDayoftheDutyVisit {
            get {
                return ResourceManager.GetString("LastDayoftheDutyVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Leave.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Advance:.
        /// </summary>
        internal static string LeaveAdvance {
            get {
                return ResourceManager.GetString("LeaveAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amendment.
        /// </summary>
        internal static string LeaveAmendment {
            get {
                return ResourceManager.GetString("LeaveAmendment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation.
        /// </summary>
        internal static string LeaveCancel {
            get {
                return ResourceManager.GetString("LeaveCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Category:.
        /// </summary>
        internal static string LeaveCategory {
            get {
                return ResourceManager.GetString("LeaveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Request.
        /// </summary>
        internal static string LeaveRequest {
            get {
                return ResourceManager.GetString("LeaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Select Confirmed if you are sure of the dates of your absence, otherwise Select Planned. Select an Leave type, and enter any other information you want to record for your request..
        /// </summary>
        internal static string LeaveRequestNote {
            get {
                return ResourceManager.GetString("LeaveRequestNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumption.
        /// </summary>
        internal static string LeaveResume {
            get {
                return ResourceManager.GetString("LeaveResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Status:.
        /// </summary>
        internal static string LeaveStatus {
            get {
                return ResourceManager.GetString("LeaveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave to be Cancelled: *.
        /// </summary>
        internal static string LeavetobeCancelled {
            get {
                return ResourceManager.GetString("LeavetobeCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type: *.
        /// </summary>
        internal static string LeaveType {
            get {
                return ResourceManager.GetString("LeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Purpose.
        /// </summary>
        internal static string LetterPurpose {
            get {
                return ResourceManager.GetString("LetterPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Type *.
        /// </summary>
        internal static string LetterType {
            get {
                return ResourceManager.GetString("LetterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L O G I N.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Min 3 Chars).
        /// </summary>
        internal static string MinChars {
            get {
                return ResourceManager.GetString("MinChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Leave End Date: *.
        /// </summary>
        internal static string NewLeaveEndDate {
            get {
                return ResourceManager.GetString("NewLeaveEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Leave Start Date: *.
        /// </summary>
        internal static string NewLeaveStartDate {
            get {
                return ResourceManager.GetString("NewLeaveStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Travel Date:.
        /// </summary>
        internal static string NewTravelDate {
            get {
                return ResourceManager.GetString("NewTravelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        internal static string PasswordErrorMessage {
            get {
                return ResourceManager.GetString("PasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdiem Amount:.
        /// </summary>
        internal static string PerdiemAmount {
            get {
                return ResourceManager.GetString("PerdiemAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdiem Paid by Host: *.
        /// </summary>
        internal static string PerdiemPaidbyHost {
            get {
                return ResourceManager.GetString("PerdiemPaidbyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Request.
        /// </summary>
        internal static string PermitRequest {
            get {
                return ResourceManager.GetString("PermitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Exit Permit is valid only for 24 Hours (From: 00:01 AM to 23.59 PM of the mentioned travel date), in case of any change in the Travel date and time. Please apply for new Exit permits through Exit Permit Request in Oracle Self Service or contact HR..
        /// </summary>
        internal static string PermitRequestNote {
            get {
                return ResourceManager.GetString("PermitRequestNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose Of Letter.
        /// </summary>
        internal static string PurposeOfLetter {
            get {
                return ResourceManager.GetString("PurposeOfLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of Visit / Remarks: *.
        /// </summary>
        internal static string PurposeofVisitRemarks {
            get {
                return ResourceManager.GetString("PurposeofVisitRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks: *.
        /// </summary>
        internal static string RemarksRq {
            get {
                return ResourceManager.GetString("RemarksRq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced By:.
        /// </summary>
        internal static string ReplacedBy {
            get {
                return ResourceManager.GetString("ReplacedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Request.
        /// </summary>
        internal static string ResumeRequest {
            get {
                return ResourceManager.GetString("ResumeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumption Date:.
        /// </summary>
        internal static string ResumptionDate {
            get {
                return ResourceManager.GetString("ResumptionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date: *.
        /// </summary>
        internal static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date: *.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time:.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Date:.
        /// </summary>
        internal static string SubmissionDate {
            get {
                return ResourceManager.GetString("SubmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S U B M I T.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket: *.
        /// </summary>
        internal static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Days:.
        /// </summary>
        internal static string TotalDays {
            get {
                return ResourceManager.GetString("TotalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours:.
        /// </summary>
        internal static string TotalHours {
            get {
                return ResourceManager.GetString("TotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Date From.
        /// </summary>
        internal static string TravelDateFrom {
            get {
                return ResourceManager.GetString("TravelDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Date To.
        /// </summary>
        internal static string TravelDateTo {
            get {
                return ResourceManager.GetString("TravelDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Destination.
        /// </summary>
        internal static string TravelDestination {
            get {
                return ResourceManager.GetString("TravelDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty..
        /// </summary>
        internal static string UsernameErrorMessage {
            get {
                return ResourceManager.GetString("UsernameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERNAME.
        /// </summary>
        internal static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Type.
        /// </summary>
        internal static string VisaType {
            get {
                return ResourceManager.GetString("VisaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hassad Employee Self Service.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string WorkList {
            get {
                return ResourceManager.GetString("WorkList", resourceCulture);
            }
        }
    }
}
